# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QFileDialog
import sys, gui

import detect, time
import win32gui


def get_visible_windows():
    # 定义一个回调函数来枚举所有可见窗口
    def enum_windows_callback(hwnd, visible_windows):
        if win32gui.IsWindowVisible(hwnd):
            visible_windows.append(hwnd)
        return True

    # 枚举所有可见窗口
    visible_windows = []
    win32gui.EnumWindows(enum_windows_callback, visible_windows)

    return visible_windows


def get_genshin_location():
    for hwnd in get_visible_windows():
        window_title = win32gui.GetWindowText(hwnd)
        if window_title == '原神':
            left, top, right, bottom = win32gui.GetWindowRect(hwnd)
            return left, top, right, bottom

    return 0, 0, 0, 0


class MainW(QMainWindow, gui.Ui_MainWindow):
    def __init__(self):
        QMainWindow.__init__(self)
        gui.Ui_MainWindow.__init__(self)
        self.setupUi(self)
        self.weight = r"D:\project\DeepStudy\yolov5\runs\train\200_16_ASFF\weights\best.pt"
        self.data = r"D:\project\DeepStudy\yolov5\models\config\data.yaml"
        self.view_img = True
        self.path_img = ""
        self.device = "0"
        self.pushButton.clicked.connect(self.getFileDir)
        self.pushButton_2.clicked.connect(self.screen)
        self.pushButton_3.clicked.connect(self.getWeightDir)
        self.pushButton_4.clicked.connect(self.getDataDir)
        self.pushButton_5.clicked.connect(self.start)
        self.ld.setText(self.data)
        self.lwe.setText(self.weight)

    def getFileDir(self):
        # 文件路径
        self.path_img, _ = QFileDialog.getOpenFileName(self.centralwidget, '打开文件', './',
                                                       'ALL(*.*)')
        # 显示图像
        self.view_img = False
        self.lf.setText(self.path_img)

    def getDataDir(self):
        # 文件路径
        self.data, _ = QFileDialog.getOpenFileName(self.centralwidget, '打开文件', './',
                                                   'ALL(*.*)')
        self.ld.setText(self.data)

    def getWeightDir(self):
        # 文件路径
        self.weight, _ = QFileDialog.getOpenFileName(self.centralwidget, '打开文件', './',
                                                     'ALL(*.*)')
        self.lwe.setText(self.weight)

    def screen(self):
        # 屏幕位置
        # 左上角，右下角
        x0, y0, x1, y1 = get_genshin_location()

        x = str(x0)
        y = y0 + y1 - 540

        if y < 0:
            print("false")
            self.close()
        y = str(y)
        self.path_img = f"screen 0 {x} {y} 960 540"

        # 显示图像
        self.lx.setText(x)
        self.ly.setText(y)
        self.lwi.setText("960")
        self.lh.setText("540")
        self.view_img = True

    def start(self):
        self.device = self.cd.currentText()
        self.close()
        self.closeEvent(detect.run(source=self.path_img, view_img=self.view_img, data=self.data, weights=self.weight,
                                   device=self.device))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    md = MainW()
    md.show()

    app.exec_()
