# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QFileDialog, QStackedWidget, QAction, QWidget, QMessageBox
import sys, detect, win32gui, gui

import train


def get_visible_windows():
    # 定义一个回调函数来枚举所有可见窗口 
    def enum_windows_callback(hwnd, visible_windows):
        if win32gui.IsWindowVisible(hwnd):
            visible_windows.append(hwnd)
        return True

    # 枚举所有可见窗口
    visible_windows = []
    win32gui.EnumWindows(enum_windows_callback, visible_windows)

    return visible_windows


def get_genshin_location():
    for hwnd in get_visible_windows():
        window_title = win32gui.GetWindowText(hwnd)
        if window_title == '原神':
            left, top, right, bottom = win32gui.GetWindowRect(hwnd)
            return left, top, right, bottom

    return 0, 0, 0, 0


class MainW(QMainWindow, gui.Ui_MainWindow):
    def __init__(self):
        QMainWindow.__init__(self)
        gui.Ui_MainWindow.__init__(self)

        self.setupUi(self)
        self.style()
        self.weight = r"D:\project\DeepStudy\yolov5\runs\train\200_16_ASFF\weights\best.pt"
        self.data = r"D:\project\DeepStudy\yolov5\models\config\data.yaml"
        self.view_img = True
        self.path_img = ""
        self.device = "0"
        self.isStart = False

        self.cfg = r"D:\project\DeepStudy\yolov5\models\yolov5s.yaml"
        self.tdata = r"D:\project\DeepStudy\yolov5\models\config\data.yaml"
        self.tweight = r"D:\project\DeepStudy\yolov5\yolov5s.pt"
        self.epochs = 100
        self.imgsz = 640
        self.tdevice = "0"
        self.batch_size = 16
        self.workers = 0
        self.isStart2 = False

        self.pushButton.clicked.connect(self.getFileDir)
        self.pushButton_2.clicked.connect(self.screen)
        self.pushButton_3.clicked.connect(self.getWeightDir)
        self.pushButton_4.clicked.connect(self.getDataDir)
        self.pushButton_5.clicked.connect(self.start)
        self.pushButton_16.clicked.connect(self.getTDataDir)
        self.pushButton_15.clicked.connect(self.getCfgDir)
        self.pushButton_14.clicked.connect(self.getTWeightDir)
        self.pushButton_6.clicked.connect(self.start2)
        self.ld.setText(self.data)
        self.lwe.setText(self.weight)
        self.ld_8.setText(self.tdata)
        self.ld_7.setText(self.cfg)
        self.ld_6.setText(self.tweight)

    def style(self):
        self.centralwidget.setStyleSheet('''
        QWidget {
            background-color: #ffffff;
        }
        ''')

        self.pushButton.setStyleSheet('''
        QPushButton {
            background-color: white;
            color: black;
            border: 2px solid #e7e7e7;
        }
        QPushButton:hover {
            background-color: #e7e7e7;
        }
        ''')
        self.pushButton_2.setStyleSheet(self.pushButton.styleSheet())
        self.pushButton_3.setStyleSheet(self.pushButton.styleSheet())
        self.pushButton_4.setStyleSheet(self.pushButton.styleSheet())
        self.pushButton_5.setStyleSheet(self.pushButton.styleSheet())
        self.pushButton_6.setStyleSheet(self.pushButton.styleSheet())
        self.pushButton_16.setStyleSheet(self.pushButton.styleSheet())
        self.pushButton_15.setStyleSheet(self.pushButton.styleSheet())
        self.pushButton_14.setStyleSheet(self.pushButton.styleSheet())

        self.cd.setStyleSheet('''
            QComboBox{
                background: white;
                color: black;
                border:2px solid #e7e7e7;
            }
            QComboBox::drop-down{
                width: 20px;
                border-left: 1px solid #e7e7e7; 
            }
        ''')
        self.cd_3.setStyleSheet(self.cd.styleSheet())

    def getFileDir(self):
        # 文件路径
        filternames = '图片视频文件(*.mp4 *.jpg *.png);;ALL(*.*)'
        # 输入文件路径
        path_img, _ = QFileDialog.getOpenFileName(self.centralwidget, '打开文件', './', filternames)
        if path_img != '':
            self.path_img = path_img
            # 显示图像
            self.view_img = False
            self.lf.setText(self.path_img)

    def getDataDir(self):
        filternames = '数据集文件(*.yaml)'
        # 数据集文件路径
        data, _ = QFileDialog.getOpenFileName(self.centralwidget, '打开文件', './', filternames)
        if data != '':
            self.data = data
            self.ld.setText(self.data)

    def getWeightDir(self):
        filternames = '权重文件(*.pt);;ALL(*.*)'
        # 权重文件路径
        weight, _ = QFileDialog.getOpenFileName(self.centralwidget, '打开文件', './', filternames)
        if weight != '':
            self.weight = weight
            self.lwe.setText(self.weight)

    def screen(self):
        # 屏幕位置
        # 左上角，右下角
        x0, y0, x1, y1 = get_genshin_location()

        x = str(x0)
        y = y0 + y1 - 540

        if y < 0:
            print("false")
            self.close()
        y = str(y)
        self.path_img = f"screen 0 {x} {y} 960 540"

        # 显示图像
        self.lx.setText(x)
        self.ly.setText(y)
        self.lwi.setText("960")
        self.lh.setText("540")
        self.view_img = True

    def start(self):
        if self.isStart:
            QMessageBox.warning(self, "警告", '推理进行中！', QMessageBox.Ok)
        elif self.path_img == "":
            QMessageBox.warning(self, "警告", '未选择输入方式', QMessageBox.Ok)
        else:
            self.isStart = True
            self.device = self.cd.currentText()
            save_dir = detect.run(source=self.path_img, view_img=self.view_img, data=self.data, weights=self.weight,
                                  device=self.device)
            result = save_dir.split('\n')[1].split(' ')[-1][:-7]
            self.textBrowser.setText('结果保存至' + result)
            self.path_img = ''
            self.lf.setText(self.path_img)
            self.isStart = False

    def getTDataDir(self):
        filternames = '数据集文件(*.yaml)'
        # 数据集文件路径
        tdata, _ = QFileDialog.getOpenFileName(self.centralwidget, '打开文件', './', filternames)
        if tdata != '':
            self.tdata = tdata
            self.ld_8.setText(self.tdata)

    def getCfgDir(self):
        # 文件路径
        filternames = '配置文件(*.yaml)'
        # 输入文件路径
        cfg, _ = QFileDialog.getOpenFileName(self.centralwidget, '打开文件', './', filternames)
        if cfg != '':
            self.cfg = cfg
            self.ld_7.setText(self.cfg)

    def getTWeightDir(self):
        filternames = '权重文件(*.pt);;ALL(*.*)'
        # 权重文件路径
        tweight, _ = QFileDialog.getOpenFileName(self.centralwidget, '打开文件', './', filternames)
        if tweight != '':
            self.tweight = tweight
            self.ld_6.setText(self.tweight)

    def start2(self):
        if self.isStart2:
            QMessageBox.warning(self, "警告", '训练进行中！', QMessageBox.Ok)
        else:
            self.isStart2 = True
            self.device = self.cd_3.currentText()
            self.epochs = self.lineEdit.text()
            self.imgsz = self.lineEdit_3.text()
            self.batch_size = self.lineEdit_2.text()
            self.workers = self.lineEdit_4.text()
            train.run(data=self.tdata, cfg=self.cfg, weights=self.tweight, img_size=self.imgsz,
                      batch_size=self.batch_size, epochs=self.epochs, workers=self.workers, device=self.tdevice)
            self.isStart2 = False

    # @classmethod
    # def setTrainResult(cls, tr):
    #     cls.textBrowser.setText(tr)


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    md = MainW()
    md.show()
    app.exec_()
